<a href="https://colab.research.google.com/github/tlsdmswn01/PyTorch_Study/blob/main/Dataset%2CDataload.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 미니 배치와 데이터 로드

### 미니 배치와 배치 크기  
- 미니배치만큼 가져가 미니 배치에 대한 비용을 계산하고 경사 하강법 수행  
- 미니배치가 다 돌아서 전체 데이터에 대한 학습이 1회 끝나면 1회 epoch가 끝난다  
- 미니배치 = batch_size

In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

### 데이터 로드하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
from torch.utils.data import TensorDataset # 텐서 데이터셋
from torch.utils.data import DataLoader # 데이터 로더

In [ ]:
dataset=TensorDataset(x_train,y_train)

In [ ]:
dataloader=DataLoader(dataset,batch_size=2, shuffle=True)

In [ ]:
class Multi(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self,x):
    return self.linear(x)

model=Multi()

optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)

In [ ]:
epochs=200

for epoch in range(epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    #print(batch_idx)
    #print(samples)

    x_train,y_train = samples

    prediction=model(x_train)

    cost=F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()


    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/200 Batch 1/3 Cost: 3.891865
Epoch    0/200 Batch 2/3 Cost: 14.569706
Epoch    0/200 Batch 3/3 Cost: 2.669566
Epoch    1/200 Batch 1/3 Cost: 4.955001
Epoch    1/200 Batch 2/3 Cost: 4.225590
Epoch    1/200 Batch 3/3 Cost: 13.939973
Epoch    2/200 Batch 1/3 Cost: 5.291218
Epoch    2/200 Batch 2/3 Cost: 11.715350
Epoch    2/200 Batch 3/3 Cost: 2.869689
Epoch    3/200 Batch 1/3 Cost: 0.395525
Epoch    3/200 Batch 2/3 Cost: 7.952284
Epoch    3/200 Batch 3/3 Cost: 12.420742
Epoch    4/200 Batch 1/3 Cost: 4.854685
Epoch    4/200 Batch 2/3 Cost: 6.815030
Epoch    4/200 Batch 3/3 Cost: 10.165215
Epoch    5/200 Batch 1/3 Cost: 4.785839
Epoch    5/200 Batch 2/3 Cost: 4.931477
Epoch    5/200 Batch 3/3 Cost: 10.656734
Epoch    6/200 Batch 1/3 Cost: 11.196382
Epoch    6/200 Batch 2/3 Cost: 7.517283
Epoch    6/200 Batch 3/3 Cost: 1.688183
Epoch    7/200 Batch 1/3 Cost: 6.393277
Epoch    7/200 Batch 2/3 Cost: 8.381448
Epoch    7/200 Batch 3/3 Cost: 0.768833
Epoch    8/200 Batch 1/3 Cost: 11

In [ ]:
new_var =  torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.5980]], grad_fn=<AddmmBackward0>)


## 커스텀 데이터셋(Custom Dataset)

In [ ]:
class CustomDataset(torch.utils.data.Dataset):
  def __init__(): # 데이터셋의 전처리를 해주는 부분


  def __len__(self): # 데이터셋의 길이, 즉 총 샘플의 수를 적어주는 부분


  def __getitem__(self): # 데이터셋에서 특정 1개의 샘플을 가져오는 함수


### 커스텀 데이터셋으로 선형회귀 구현

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Multi(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(3,1)

  def forward(self,x):
    return self.linear(x)

model= Multi()
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)

In [ ]:
class CustomDataset(torch.utils.data.Dataset): # 데이터셋 상속

  def __init__(self):
    self.x_train=[[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_train=[[152], [185], [180], [196], [142]]

  def __len__(self): # 총 데이터의 개수를 리턴
    return len(self.x_train)

  def __getitem__(self,idx): # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor형태로 리턴
    x= torch.FloatTensor(self.x_train[idx])
    y= torch.FloatTensor(self.y_train[idx])
    return x,y


In [ ]:
dataset=CustomDataset()
dataloader= DataLoader(dataset,batch_size=2, shuffle=True)

In [ ]:
len(dataset)

5

In [ ]:
epochs=200
for epoch in range(epochs+1):
  for idx,samples in enumerate(dataloader):
    x_train,y_train=samples

    prediction=model(x_train)

    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch,epochs, idx+1, len(dataloader),
        cost.item()
        ))


Epoch    0/200 Batch 1/3 Cost: 1.638588
Epoch    0/200 Batch 2/3 Cost: 0.535669
Epoch    0/200 Batch 3/3 Cost: 4.284488
Epoch    1/200 Batch 1/3 Cost: 1.892740
Epoch    1/200 Batch 2/3 Cost: 1.983831
Epoch    1/200 Batch 3/3 Cost: 0.310376
Epoch    2/200 Batch 1/3 Cost: 1.678714
Epoch    2/200 Batch 2/3 Cost: 1.294721
Epoch    2/200 Batch 3/3 Cost: 2.267521
Epoch    3/200 Batch 1/3 Cost: 2.292578
Epoch    3/200 Batch 2/3 Cost: 0.707180
Epoch    3/200 Batch 3/3 Cost: 2.589007
Epoch    4/200 Batch 1/3 Cost: 1.183115
Epoch    4/200 Batch 2/3 Cost: 2.072431
Epoch    4/200 Batch 3/3 Cost: 1.725221
Epoch    5/200 Batch 1/3 Cost: 1.720603
Epoch    5/200 Batch 2/3 Cost: 1.971305
Epoch    5/200 Batch 3/3 Cost: 1.575573
Epoch    6/200 Batch 1/3 Cost: 0.737371
Epoch    6/200 Batch 2/3 Cost: 1.998468
Epoch    6/200 Batch 3/3 Cost: 2.545879
Epoch    7/200 Batch 1/3 Cost: 1.601002
Epoch    7/200 Batch 2/3 Cost: 1.698165
Epoch    7/200 Batch 3/3 Cost: 2.074398
Epoch    8/200 Batch 1/3 Cost: 0.759430


In [ ]:
new_var=torch.FloatTensor([[73,85,79]])
pred_y=model(new_var)
print(pred_y)
print(list(model.parameters()))

tensor([[158.6103]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.9310, 0.7451, 0.3399]], requires_grad=True), Parameter containing:
tensor([0.4646], requires_grad=True)]
