<a href="https://colab.research.google.com/github/tlsdmswn01/PyTorch_Study/blob/main/nn_Module%EB%A1%9C_%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94_%EC%84%A0%ED%98%95_%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 선형회귀모델


In [ ]:
import torch.nn as nn
#model= nn.Linear(input_dim, output_dim)

NameError: name 'input_dim' is not defined

In [ ]:
# 평균 제곱오차 mse
import torch.nn.functional as F
cost = F.mse_loss(prediction, y_train)

### 단순 선형 회귀 구현

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [ ]:
# 데이터 선언 y=2x가 가정된 상태에서 만들어진 데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

# 모델 선언 및 초기화, 단순 선형 회귀이므로 input_dim = 1, output_dim=1
model=nn.Linear(1,1)
# 하나의 입력 x에 대해서 하나의 출력 y를 가짐으로 입력과 출력 차원 모두 1을 인수로 사용
print(list(model.parameters())) # 출력되는 각 값들이 현재는 랜덤 초기화 되어 있음
# 첫번째 출력값 : 가중치 w
# 두번째 출력값 : 편향 b

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
# 옵티마이저 정의, model.parameters()를 사용하여 W와 b를 전달합니다.학습률(learning rate)은 0.01로 정합니다.
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch. optim. SGD(model.parameters(),lr=0.01)

In [ ]:
# 전체 훈련 데이터에 대해 경사 하강법 2,000회 반복

nb_epochs=2000
for epoch in range(nb_epochs+1):

  #예측값 계산
  prediction = model(x_train)

  #cost 계산
  cost=F.mse_loss(prediction, y_train) #  <== 파이토치에서 제공하는 평균 제곱 오차 함수

  #cost로 예측값 개선하는 부분
  #gradient를 0으로 초기화
  optimizer.zero_grad()

  #비용 함수를 미분하여 gradient를 계산
  cost.backward() #backward연산, 미분

  #w와 b를 업데이트
  optimizer.step()

  if epoch%100==0:
    #100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))


Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


-  w와 b값이 최적화 되었는지 확인
- x에 임의의 값 4를 넣어 모델이 예측하는 y의 값을 확인


In [ ]:
# 임의의 입력 4를 선언
new_var=torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아 pred_y에 저장
pred_y=model(new_var) # forward연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


- y=2x가 정답이므로 4를 입력했을 떄 8에 매우 가까우면 w와 b 값이 어느정도 최적화 된 것으로 볼수 있다.

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


### 다중 선형 회귀 구현

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# 3개의 x로부터 하나의 y를 예측하는 문제
# 데이터 정의
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

In [ ]:
print(list(model.parameters())) # 3개의 w값과 1개의 b값 -> 랜덤 초기화 되어있는 상

[Parameter containing:
tensor([[ 0.1286,  0.3306, -0.1909]], requires_grad=True), Parameter containing:
tensor([0.5474], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(),lr=1e-5)

In [ ]:
nb_epochs=2000

for epoch in range(nb_epochs+1):

  #H(x) 계산
  prediction= model(x_train)
  # model(x_train)은 model.forward(x_train)과 동일

  #cost 계산
  cost= F.mse_loss(prediction, y_train)

  #cost로 H(x) 개선하는 부분
  #gradient 0으로 초기화
  optimizer.zero_grad()
  #비용함수를 미분하여 gradient를 계산
  cost.backward()
  #w와 b를 업데이트
  optimizer.step()

  if epoch%100==0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 22204.394531
Epoch  100/2000 Cost: 3.543473
Epoch  200/2000 Cost: 3.364566
Epoch  300/2000 Cost: 3.195100
Epoch  400/2000 Cost: 3.034569
Epoch  500/2000 Cost: 2.882482
Epoch  600/2000 Cost: 2.738466
Epoch  700/2000 Cost: 2.602028
Epoch  800/2000 Cost: 2.472766
Epoch  900/2000 Cost: 2.350355
Epoch 1000/2000 Cost: 2.234386
Epoch 1100/2000 Cost: 2.124547
Epoch 1200/2000 Cost: 2.020495
Epoch 1300/2000 Cost: 1.921939
Epoch 1400/2000 Cost: 1.828601
Epoch 1500/2000 Cost: 1.740134
Epoch 1600/2000 Cost: 1.656371
Epoch 1700/2000 Cost: 1.577023
Epoch 1800/2000 Cost: 1.501846
Epoch 1900/2000 Cost: 1.430652
Epoch 2000/2000 Cost: 1.363207


- x에 임의의 입력 [73,80,75]를 넣어 모델이 예측하는 y의 값을 확인해보기

In [ ]:
new_var=torch.FloatTensor([[73,80,75]])
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.1346]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8388, 0.7416, 0.4269]], requires_grad=True), Parameter containing:
tensor([0.5556], requires_grad=True)]
