<a href="https://colab.research.google.com/github/tlsdmswn01/PyTorch_Study/blob/main/%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A1%9C_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EB%AA%A8%EB%8D%B8_%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0_ipynby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 모델을 클래스로 구현하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# 모델을 선언 및 초기화. 단순 선형 회귀로 input_dim=1. output_dim=1
model=nn.Linear(1,1)

In [ ]:
# 클래스로 구현
class LinearRegressionModel(nn.Module): #torch.nn.Module을 상속받는 파이썬 클래스
  def __init__(self): # 모델의 구조와 동작을 정의하는 생성자
    super().__init__() # nn.Module 클래스의 속성들을 가지고 초기화
    self.linear=nn.Linear(1,1)

  def forward(self,x): #forward() 함수는 model 객체를 데이터와 함께 호출하면 자동으로 실행
    return self.linear(x)

In [ ]:
model = LinearRegressionModel()

In [ ]:
class MultiLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(3,1)

  def forward(self,x):
    return self.linear(x)


In [ ]:
model=MultiLinearRegressionModel()

### 단순 선형 회귀 클래스 구현


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
class Linearregression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(1,1)

  def forward(self,x):
    return self.linear(x)


In [ ]:
model=Linearregression()

In [ ]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

In [ ]:
nb_epochs=2000
for epoch in range(nb_epochs+1):

  #H(x)계산
  prediction=model(x_train)

  #cost 계산
  cost=F.mse_loss(prediction, y_train)

  #optim 0으로 초기화
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print('Epoch{:4d}/{} Cost:{:6f}'.format(epoch,nb_epochs,cost.item()))

Epoch   0/2000 Cost:10.358571
Epoch 100/2000 Cost:0.002777
Epoch 200/2000 Cost:0.001716
Epoch 300/2000 Cost:0.001060
Epoch 400/2000 Cost:0.000655
Epoch 500/2000 Cost:0.000405
Epoch 600/2000 Cost:0.000250
Epoch 700/2000 Cost:0.000155
Epoch 800/2000 Cost:0.000096
Epoch 900/2000 Cost:0.000059
Epoch1000/2000 Cost:0.000036
Epoch1100/2000 Cost:0.000023
Epoch1200/2000 Cost:0.000014
Epoch1300/2000 Cost:0.000009
Epoch1400/2000 Cost:0.000005
Epoch1500/2000 Cost:0.000003
Epoch1600/2000 Cost:0.000002
Epoch1700/2000 Cost:0.000001
Epoch1800/2000 Cost:0.000001
Epoch1900/2000 Cost:0.000000
Epoch2000/2000 Cost:0.000000


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


### 다중 선형회귀 모델

In [ ]:
class Multi(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(3,1)

  def forward(self,x):
    return self.linear(x)

In [ ]:
model=Multi()

In [ ]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)

In [ ]:
epochs=2000
for epoch in range(epochs+1):

  prediction=model(x_train)

  cost=F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()


  if epoch%100==0:

    print('Epoch:{:4d}/{} Cost:{}'.format(epoch,epochs,cost.item()))

Epoch:   0/2000 Cost:19085.046875
Epoch: 100/2000 Cost:0.9540506601333618
Epoch: 200/2000 Cost:0.9251181483268738
Epoch: 300/2000 Cost:0.8976455926895142
Epoch: 400/2000 Cost:0.8715797662734985
Epoch: 500/2000 Cost:0.8468269109725952
Epoch: 600/2000 Cost:0.8233121037483215
Epoch: 700/2000 Cost:0.8009885549545288
Epoch: 800/2000 Cost:0.7797815203666687
Epoch: 900/2000 Cost:0.7596341371536255
Epoch:1000/2000 Cost:0.7404940724372864
Epoch:1100/2000 Cost:0.7223042249679565
Epoch:1200/2000 Cost:0.7050129771232605
Epoch:1300/2000 Cost:0.6885821223258972
Epoch:1400/2000 Cost:0.6729573011398315
Epoch:1500/2000 Cost:0.658107578754425
Epoch:1600/2000 Cost:0.643979549407959
Epoch:1700/2000 Cost:0.63054358959198
Epoch:1800/2000 Cost:0.6177762746810913
Epoch:1900/2000 Cost:0.6056073904037476
Epoch:2000/2000 Cost:0.5940291881561279


In [ ]:
prediction=model(x_train)
print(prediction,y_train)

tensor([[151.7087],
        [184.4086],
        [180.6366],
        [196.9685],
        [140.9084]], grad_fn=<AddmmBackward0>) tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])
